# config/deploy.yml
service: monobase
image: ghcr.io/we-are-mono/monobase

proxy:
  ssl: false
  ssl_redirect: false

servers:
  web:
    hosts:
      - nebula
    options:
      volume:
        - /var/lib/monobase/storage:/rails/storage

registry:
  server: ghcr.io
  username: depy
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  remote: false
  arch: amd64

env:
  secret:
    - RAILS_MASTER_KEY
